dimension = 1
horizon = 3.014

[[Grid]]
    path = "twopoints.grid"

[MaterialDefault]
    id = 1
    density = 10.4


[[BC]]
    displacement = [0, 0, 0]
    [[BC.include]]
        sphere = [0,0,0,10]
    [[BC.exclude]]
        cuboid = [0, 0, 0, 1, 1, 1]
    [[BC.exclude]]
        sphere = [0, 0, 0, 1, 1, 1]
    [[BC.exclude]]
        material = 1

[Output]
