gridspacing = 0.2
horizon = 0.603


[[Grid]]
    path = "holeplate.grid"

[MaterialDefault]
    type = "LinearElastic"
    id = 1
    density = 10.4
    bond_constant = 1.0
    critical_strain = 0.2

[[BC]]
    type = "Staged Loading"
    increment = [-0.1, 0.0, 0.0]
    volume = [-65,-59,-9999,9999,-9999,9999]

[[BC]]
    type = "Staged Loading"
    increment = [0.1, 0.0, 0.0]
    volume = [59,65,-9999, 9999,-9999,9999]
