gridspacing = 1.0
horizon = 3.015


[[Grid]]
    path = "pants.grid"

[MaterialDefault]
    type = "LinearElastic"
    id = 1
    density = 10.4
    bond_constant = 1.0
    critical_strain = 0.1

[[BC]]
    type = "Displacement"
    displacement = [0.0, 0.0, 0.0]
    volume = [-25, 25, -25, -24, -1, 1]

[[BC]]
    type = "Staged Loading"
    increment = [-0.25, 0.0, 0.0]
    volume = [-25,0,24,25,-9999,9999]

[[BC]]
    type = "Staged Loading"
    increment = [0.25, 0.0, 0.0]
    volume = [0 , 25, 24, 25,-9999,9999]

[[NoFail]]
    volume = [-25 , 25, 24, 25,-9999,9999]

[[NoFail]]
    volume = [-25 , 25, -25, -24,-9999,9999]