gridspacing = 2.0
horizon = 6.03

[[Grid]]
    path = "twopoints.grid"

[MaterialDefault]
    type = "LinearElastic"
    id = 1
    density = 10.4
    bond_constant = 1.0
    critical_strain = 0.2

#[[BC]]
#    type = "Velocity"
#    velocity = [0, 0, 0]
#    volume = [10, 20, -10, 10, -10, 10]

[[BC]]
    type = "Displacement"
    displacement = [0, 0, 0]
    volume = [-0.5,0.5,-1,1,-1,1]


[[ForceProbe]]
    type = "Plane"
    pointOnPlane = [0.5, 0, 0]
    normal = [1, 0, 0]


