dimension = 1
gridspacing = 2.0
horizon = 6.03

[[Grid]]
    path = "twopoints.grid"

[MaterialDefault]
    type = "LinearElastic"
    id = 1
    density = 10.4
    bond_constant = 1.0
    critical_strain = 0.2
    
[[Material]]
    type = "LinearElastic"
    id = 2
    density = 12.2
    bond_constant = 3.1
    critical_strain = 0.14

[[Material]]
    type = "CustomMaterial"
    id = 3
    density = 12.2


[[BC]]
    type = "Displacement"
    displacement = [0, 0, 0]
    [[BC.include]]
        sphere = [0,0,0,10]
    [[BC.exclude]]
        cuboid = [0, 0, 0, 1, 1, 1]
    [[BC.exclude]]
        sphere = [0, 0, 0, 1, 1, 1]
    [[BC.exclude]]
        material = 1

[Output]
