gridspacing = 1.0
horizon = 3.015


[[Grid]]
    path = "examples/StringContactTest/contactStrings.grid"

[MaterialDefault]
    # Glass plate
    # sspnom = 2600
    # density = 2200
    # ... k = 14,872,000,000
    # stable time step = gridspacing / sqrt(k / density) = gridspacing / sspnom
    type = "LinearElastic"
    id = 1
    density = 220000000.0
    # 18k / (pi*horizon)
    bond_constant = 28417834394.90446
    critical_strain = 0.02

[Contact]
    distance = 1.0
    coefficient = 1000000000000.0


[[NoFail]]
    volume = [-999, 999, -999, 999, -999, 999]

[[Disconnect]]
    ids = [1, 2]

# Move vertical string
[[BC]]
    type = "Staged Loading"
    increment = [0.0, -2.0, 0.0]
    volume = [-9999, 9999, -9999, 9999, 21, 25]

[[BC]]
    type = "Staged Loading"
    increment = [0.0, -2.0, 0.0]
    volume = [-9999, 9999, -9999, 9999, -25, -21]


# Hold horizontal string
[[BC]]
    type = "Displacement"
    displacement = [0.0, 0.0, 0.0]
    volume = [21, 25, -9999, 9999, -9999, 9999]

[[BC]]
    type = "Displacement"
    displacement = [0.0, 0.0, 0.0]
    volume = [-25, -21, -9999, 9999, -9999, 9999]
