gridspacing = 1.0
horizon = 3.015


[[Grid]]
    path = "examples/ContactTest/plate.grid"
[[Grid]]
    path = "examples/ContactTest/impactor.grid"

[MaterialDefault]
    # Glass plate
    # sspnom = 2600
    # density = 2200
    # ... k = 14,872,000,000
    # stable time step = gridspacing / sqrt(k / density) = gridspacing / sspnom
    type = "LinearElastic"
    id = 1
    density = 22000000000.0
    # 18k / (pi*horizon)
    bond_constant = 28417834394.90446
    critical_strain = 0.001

[[Material]]
    type = "LinearElastic"
    id = 2
    density = 22000000000.0
    bond_constant = 1000000000000.0
    critical_strain = 0.2

