gridspacing = 2.0
horizon = 6.03

[[Grid]]
    path = "examples/TwoPoint/twopoints.grid"

[MaterialDefault]
    type = "LinearElastic"
    id = 1
    density = 10.4
    bond_constant = 1.0
    critical_strain = 1.2

[[BC]]
    type = "Displacement"
    displacement = [0, 0, 0]
    volume = [1.5,2.5,-1.0,1.0,-1.0,1.0]

[[BC]]
    type = "Displacement"
    displacement = [0, 0, 0]
    volume = [-0.5,0.5,-1.0,1.0,-1.0,1.0]


[[ForceProbe]]
    type = "Plane"
    pointOnPlane = [0.5, 0.0, 0.0]
    normal = [1, 0, 0]


