gridspacing = 1.0
horizon = 3.015

[[Grid]]
    path="examples/PlasticBehaviorValidation/twopoints.grid"

[MaterialDefault]
    type="CustomPlastic"
    id = 1
    density=1
    critical_strain=0.1
    bond_constant=40
    path = "examples/PlasticBehaviorValidation/force_response.csv"

[[BC]]
    type="Displacement"
    displacement=[0,0,0]
    volume=[-0.5, 0.5, -0.5, 0.5, -0.5, 0.5]

[[ForceProbe]]
    type="plane"
    point_on_plane=[0.5, 0.0, 0.0]
    normal=[1,0,0]